version: '3.6'

services:
  web:
    image: wasm:latest
    hostname: conway
    pid: host
    restart: always
    ports:
      - "8080:8080"
    container_name: conway
    entrypoint: "./entrypoint.sh"
    volumes:
      - ./:/conway
    working_dir: /conway
    networks:
      net:
        aliases:
          - web
        ipv4_address: 172.42.0.2
    healthcheck:
      test: ["CMD", "/usr/local/bin/healthcheck"]
      interval: 10s
      timeout: 10s
      retries: 3

networks:
  net:
    external:
      name: web
